### ISSUE TITLE
Add collectionCode in Saltabel

### ISSUE THREAD

**Issue by DimEvil** [LifeWatchINBO/saltabel-occurrences#15]
In Recorder, in comments, there is a link to the original collection were the record originated from. This should be under the term collectionCode in the saltabel Darwin Core Archive. 
Example: Collection: KBIN
We search the values before the ||

**Comment by peterdesmet** [comment]
Listed in https://github.com/LifeWatchINBO/data-publication/issues/57, not yet done. Closing here.
